services:
  bot:
    image: ghcr.io/greek/toilet-bot:master
    restart: always
    networks:
      - 'tnet'
    environment:
      - DISCORD_PREFIX=${DISCORD_PREFIX}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGO_DB=${MONGO_DB}
      - MONGO_NAME=${MONGO_NAME:-toilet}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_URL=redis://${REDIS_USERNAME:-default}:${REDIS_PASS}@${REDIS_HOST:-192.168.92.10:6379}/
      - LAST_FM_KEY=${LAST_FM_KEY}
      - LAST_FM_SECRET=${LAST_FM_SECRET}
    depends_on:
      - redis

  redis:
    image: redis:7.0.4
    networks:
      tnet:
        ipv4_address: 192.168.92.10
    restart: always
    ports:
      - '6379:6379'
    command: "redis-server --save 20 1 --loglevel warning"

networks:
  tnet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"