services:
  database:
    container_name: toilet-dev-db
    image: postgres
    environment:
      - POSTGRES_USER=toilet
      - POSTGRES_PASSWORD=toilet
      - POSTGRES_DB=toilet
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql

  redis:
    container_name: toilet-dev-temp-store
    image: redis:7.0.4
    restart: always
    command: "redis-server /usr/local/etc/redis/redis.conf --save 20 1 --loglevel warning"
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - cache:/data

  mongo:
    container_name: toilet-mongo-store
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - 27017:27017

volumes:
  cache:
    driver: local