services:
  database:
    container_name: database-dev
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  redis:
    container_name: redis-dev
    image: redis:7.0.4
    restart: always
    command: "redis-server /usr/local/etc/redis/redis.conf --save 20 1 --loglevel warning"
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/cache:/data

  mongo:
    container_name: mongo-dev
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toilet
    ports:
      - 27017:27017
    volumes:
      - './mongo/data/:/data/db'

# volumes:
  # cache:
  #   driver: local